version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: ms_prueba_flink
    container_name: ms_prueba_flink
    restart: unless-stopped
    command: node app.js

volumes:
  node_modules: